# Generated by Django 5.2.5 on 2025-08-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo para la propiedad (Ej: Casa en zona céntrica)', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa de la propiedad.')),
                ('tipo', models.CharField(choices=[('casa', 'Casa - Vivienda unifamiliar'), ('apartamento', 'Apartamento - Unidad en edificio'), ('terreno', 'Terreno - Solar o lote'), ('local_comercial', 'Local Comercial - Espacio para negocios'), ('oficina', 'Oficina - Espacio de trabajo'), ('galpon', 'Galpón - Depósito o bodega'), ('deposito', 'Depósito - Lugar de almacenamiento'), ('otro', 'Otro - Otro tipo de propiedad')], help_text='Selecciona el tipo de propiedad.', max_length=50)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], help_text='Selecciona si es en venta o alquiler.', max_length=50)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en dólares americanos (USD). Opcional.', max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en pesos argentinos (ARS). Opcional.', max_digits=12, null=True)),
                ('direccion', models.CharField(help_text='Dirección completa de la propiedad.', max_length=255)),
                ('localidad', models.CharField(help_text='Localidad o barrio donde se encuentra la propiedad.', max_length=100)),
                ('provincia', models.CharField(help_text='Provincia o estado.', max_length=100)),
                ('pais', models.CharField(default='Argentina', help_text='País donde está ubicada la propiedad.', max_length=100)),
                ('metros_cuadrados_total', models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados totales del terreno.', max_digits=8, null=True)),
                ('metros_cuadrados_cubierta', models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados cubiertos (construidos).', max_digits=8, null=True)),
                ('dormitorios', models.IntegerField(blank=True, help_text='Cantidad de dormitorios.', null=True)),
                ('banios', models.IntegerField(blank=True, help_text='Cantidad de baños.', null=True)),
                ('cocheras', models.IntegerField(blank=True, help_text='Cantidad de cocheras o estacionamientos.', null=True)),
                ('antiguedad', models.IntegerField(blank=True, help_text='Años de antigüedad de la propiedad.', null=True)),
                ('amenidades', models.TextField(blank=True, help_text='Lista de amenidades separadas por comas (Ej: pileta, parque, gimnasio).')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal para mostrar en listados y detalle.', null=True, upload_to='propiedades/imagenes_principal/')),
                ('is_destacada', models.BooleanField(default=False, help_text='Marcar para destacar esta propiedad en la página principal.')),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', help_text='Estado actual de publicación de la propiedad.', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen adicional de la propiedad.', upload_to='propiedades/galeria/')),
                ('descripcion_corta', models.CharField(blank=True, help_text='Breve descripción de la imagen.', max_length=100)),
                ('propiedad', models.ForeignKey(help_text='Propiedad a la que pertenece esta imagen.', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
        ),
    ]
