# Generated by Django 5.2.5 on 2025-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='acepta_mascotas',
            field=models.BooleanField(default=False, help_text='Indica si la propiedad acepta mascotas.'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_mascota_permitida',
            field=models.CharField(choices=[('no_especificado', 'No especificado'), ('perros', 'Perros'), ('gatos', 'Gatos'), ('otros', 'Otros')], default='no_especificado', help_text='Tipo de mascota permitida en la propiedad.', max_length=20),
        ),
    ]
