# Generated by Django 5.2.5 on 2025-08-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_acepta_mascotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local_comercial', 'Local Comercial'), ('oficina', 'Oficina'), ('galpon', 'Galpón'), ('deposito', 'Depósito'), ('otro', 'Otro')], help_text='Selecciona el tipo de propiedad.', max_length=50),
        ),
    ]
