# Generated by Django 5.2.5 on 2025-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_alter_propiedad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='banios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='cocheras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='dormitorios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
