# Generated by Django 5.2.5 on 2025-08-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_propiedad_banios_alter_propiedad_cocheras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='codigo_unico',
            field=models.CharField(blank=True, editable=False, help_text='Código interno de 3 letras y 3 números, generado automáticamente.', max_length=6, null=True, unique=True),
        ),
    ]
